# -*- coding: utf-8 -*-
"""regexpression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bu9pO3keemakyNJE9xt22CRu0XrGPqiG
"""

# The re.search() method takes a regular expression pattern and a string
# and searches for that pattern within the string
#Syntax
# match = re.search(pat,str)

import re



import re
txt = "The rain in spain"
x = re.search(r"^The.*Spain$",txt)

if x:
  print("YES! We have a match!")
else:
  print("No Match")

str = 'an example word:cat!!'
match = re.search('word:\w\w\w', str)

if match:
  print('found', match.group())
else:
  print('did not find')

str1 = 'Joke:what do you call a pig with three eyes? piiig!'
match = re.search(r'iii', 'piiig')

if match:
  print('found',match.group())
else:
  print('not Found')

match = re.search(r'igs', 'piiig')

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'Joke', str1)

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'ok', 'Joke')

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'.iii.', str1)

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'\d\d\d', 'p123g')

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'\w\w\w', 'p123acbg')

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'\w\w\w', '!1@#$acbg')

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r'pi+','piiit')

if match:
  print('found', match.group())
else:
  print('not found')

match = re.search(r'i+','piiitiii')

if match:
  print('found', match.group())
else:
  print('not found')

match = re.search(r'\d\s*\d\s*\d','xx1 2   3xx')

if match:
  print(r'found',match.group())
else:
  print('Not Found')

match = re.search(r'\d\s*\d\s*\d', 'xx12  3xx')

if match:
  print('found',match.group())
else:
  print("Not found")

match = re.search(r'\s*\s*', 'xx12  3xx')

if match:
  print('found',match.group())
else:
  print("Not found")

match = re.search(r'\d\s*\d\s*\d', 'xx123xx')

if match:
  print('found',match.group())
else:
  print('Not Found')

match = re.search(r' ^b\w+', 'foobar')

if match:
  print('found', match.group())
else:
  print("Not Found")

match = re.search(r'b\w+','foobar')

if match:
  print(r'found',match.group())
else:
  print("Not found")

match = re.search(r'o\w+','foobar')

if match:
  print(r'found',match.group())
else:
  print("Not found")

str = 'purple alice-b@google.com monkey dishwasher'
match = re.search(r'\w+@\w+', str)

if match:
  print('found email',match.group())
else:
  print('Not Found Email')

str2 = 'being my_mail-is@google.com as a admin'
match = re.search(r'[\w.-]+@[\w.-]+',str2)

if match:
  print('found email as: ', match.group())
else:
  print('Not Found')

match = re.search(r'([\w.-]+)@([\w.-]+)', str2)

if match:
  print('found email:',match.group())
  print('\nfound username as: ', match.group(1))
  print('\nfound the host as : ', match.group(2))
else:
  print('Not Found')

str3 = 'purple alice_b@google.com, blah monkey bob.123@abc.com blah dishwaher'
emails = re.findall(r'[\w\.-]+@[\w\.-]+', str3)
print("The Email Id's in the given data are:")
for emails in emails:
  print('\t',emails)

str3 = 'purple alice_b@google.com, blah monkey bob.123@abc.com blah dishwaher'
emails = re.findall(r'[\w\.-]+@[\w\.-]+', str3)
print("The Email Id's in the given data are:")
for emails in emails:
  print('\t',emails)

f = open('ex26.txt','r')
strings = re.findall(r'e\w+', f.read())
for strings in strings:
  print(strings)

str3 = 'purple alice_b@google.com, blah monkey bob.123@abc.com blah dishwaher'
tuples = re.findall(r'([\w\.-]+)@([\w\.-]+)', str3)
print(tuples)
for tuple in tuples:
  print('Username: ',tuple[0])
  print('Host: ',tuple[1])

rep = re.sub(r'([\w\.-]+)@([\w\w.-]+)',r'\1@yo-yo-dyne.com', str3)
print(rep)

rep = re.sub(r'([\w\.-]+)@([\w\w.-]+)',r'\1@yo-yo-dyne.com', str3)
print(rep)